#!/usr/bin/env bash
# run_matrix.sh <pgurl> [outfile]
#
# Runs every scenario against one cluster and prints a markdown report.
# The URL must connect as an admin user (root on the local demo clusters).
# Iteration counts can be overridden with N (single-row statements) and
# N500 (500-row statements).
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$HERE/.."
url="$1"; out="${2:-/dev/stdout}"
N="${N:-1000}"; N500="${N500:-200}"
# shellcheck source=queries.sh
source "$HERE/queries.sh"

run() { "$HERE/run_scenario.sh" "$url" "$@"; }
header() {
  echo
  echo "| scenario | executions | generic plans | avg planning (µs) | avg run (µs) | client avg (µs) | UDF body executions |"
  echo "|---|---|---|---|---|---|---|"
}
FG="SET plan_cache_mode = force_generic_plan"

version="$(psql "$url" -XAtqc 'SELECT version()' | awk '{print $3}')"
{
echo "# Results for CockroachDB $version"
echo
echo "Generated by \`scripts/run_matrix.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC'). Single-row statements run $N times; 500-row statements run $N500 times. Each run is one connection that prepares the statement once and executes it repeatedly through libpq."

echo
echo "## A. Prepared statements, plan_cache_mode = auto (default)"
header
run mb_udf          "$N" "$Q_MB_UDF"
run mb_inline_sql   "$N" "$Q_MB_SQL"
run nvl_udf         "$N" "$Q_NVL_UDF"
run nvl_inline_case "$N" "$Q_NVL_CASE"
run nvl_coalesce    "$N" "$Q_NVL_COALESCE"

echo
echo "## B. plan_cache_mode = force_generic_plan"
header
run mb_udf_force_generic          "$N" "$Q_MB_UDF" "$FG"
run nvl_udf_force_generic         "$N" "$Q_NVL_UDF" "$FG"
run nvl_inline_case_force_generic "$N" "$Q_NVL_CASE" "$FG"

echo
echo "## C. Is the cached plan reused? (trace of 6 executions per call shape)"
echo
"$HERE/trace_reuse.sh" "$url"

echo
echo "## D. Database-side mitigations (application SQL unchanged)"
echo
echo "Rows marked *before* use the UDFs from \`sql/02_udfs.sql\`. Rows marked *after* run the same SQL after \`sql/03_mitigations.sql\`, which drops STRICT from months_between and adds exact-typed nvl overloads."
header
run nvl_varchar_literal_force_generic_before "$N"    "$Q_NVL_VARCHAR" "$FG"
run 500rows_mb_udf_strict_before             "$N500" "$Q500_MB_UDF"
psql "$url" -Xq -f "$ROOT/sql/03_mitigations.sql" >/dev/null 2>&1
run nvl_varchar_literal_force_generic_after  "$N"    "$Q_NVL_VARCHAR" "$FG"
run 500rows_mb_udf_not_strict_after          "$N500" "$Q500_MB_UDF"
psql "$url" -Xq -f "$ROOT/sql/04_revert_mitigations.sql" >/dev/null 2>&1
run 500rows_mb_inline_sql                    "$N500" "$Q500_MB_SQL"

echo
echo "## E. UDF not inlined because an argument needs a cast (no DB-side fix)"
echo
echo "\`attr_005\` and \`attr_009\` are NUMERIC(20,4). Passing them to the unconstrained numeric parameter of \`oracompat.nvl\` adds an implicit cast, which blocks inlining (VARCHAR(n) columns behave the same way). The UDF then runs as a separate routine for every row. On v26.3 these calls do reuse the cached plan, so this section isolates the per-row cost."
header
run 500rows_nvl_udf_not_inlined "$N500" "$Q500_NVL_UDF"
run 500rows_coalesce            "$N500" "$Q500_NVL_COALESCE"

if [[ "$url" == *"root@"* ]]; then
  app_url="${url/root@/app_user@}"
  echo
  echo "## F. Role-level default instead of a session SET (no application change)"
  echo
  echo "\`ALTER ROLE app_user IN DATABASE udfdemo SET plan_cache_mode = 'force_generic_plan'\`, then connect as the non-admin \`app_user\`."
  header
  psql "$url" -Xqc "ALTER ROLE app_user IN DATABASE udfdemo SET plan_cache_mode = 'force_generic_plan'" >/dev/null 2>&1
  STATS_URL="$url" "$HERE/run_scenario.sh" "$app_url" app_user_role_default_nvl_udf "$N" "$Q_NVL_UDF"
  STATS_URL="$url" "$HERE/run_scenario.sh" "$app_url" app_user_role_default_mb_udf  "$N" "$Q_MB_UDF"
  psql "$url" -Xqc "ALTER ROLE app_user IN DATABASE udfdemo RESET plan_cache_mode" >/dev/null 2>&1
fi
} > "$out"
