#!/usr/bin/env python3
"""Generates sql/01_schema.sql.

The tables are deliberately wide (~220 and ~45 columns), as is typical for
schemas migrated from Oracle, and are queried through synonym-style views.
Planning cost grows with the number of columns the optimizer has to build, so
narrow toy tables would hide most of the effect.
"""
import pathlib

FILLER_TYPES = ["VARCHAR(20)", "NUMERIC(20,4)", "TIMESTAMP", "CHAR(1)"]


def wide_table(name, n_cols, named, pk_name, pk_cols, prefix):
    cols = [named.get(i, f"{prefix}{i:03d} {FILLER_TYPES[i % 4]}") for i in range(1, n_cols + 1)]
    cols.append(f"CONSTRAINT {pk_name} PRIMARY KEY ({', '.join(pk_cols)})")
    return f"CREATE TABLE core.{name} (\n  " + ",\n  ".join(cols) + "\n);\n"


account_master = wide_table(
    "account_master", 223,
    {1: "account_id VARCHAR(16) NOT NULL",
     20: "opened_at TIMESTAMP",
     51: "last_txn_at TIMESTAMP",
     84: "currency_code VARCHAR(3)",
     148: "bank_code VARCHAR(8) NOT NULL"},
    "account_master_pk", ["account_id", "bank_code"], "attr_")

account_advance = wide_table(
    "account_advance", 45,
    {1: "account_id VARCHAR(16) NOT NULL",
     2: "seq_no VARCHAR(5) NOT NULL",
     4: "active_flag CHAR(1) NOT NULL",
     5: "deleted_flag CHAR(1) NOT NULL",
     8: "advance_amount NUMERIC(20,4)",
     39: "bank_code VARCHAR(8) NOT NULL"},
    "account_advance_pk", ["account_id", "bank_code", "active_flag", "deleted_flag", "seq_no"], "col_")

sql = f"""-- Generated by tools/gen_schema.py. Do not edit by hand.
CREATE DATABASE IF NOT EXISTS udfdemo;
USE udfdemo;
CREATE SCHEMA IF NOT EXISTS core;

{account_master}
{account_advance}
-- Synonym-style views, as commonly created after an Oracle migration.
CREATE VIEW core.acct AS SELECT * FROM core.account_master;
CREATE VIEW core.adv AS SELECT * FROM core.account_advance;

-- 50k accounts, 150k advances (3 per account).
INSERT INTO core.account_master (account_id, bank_code, opened_at, last_txn_at, currency_code, attr_003, attr_004, attr_005)
SELECT 'A' || lpad(i::STRING, 7, '0'), 'BANK01',
       '2015-01-31'::TIMESTAMP + (i % 3000) * INTERVAL '1 day',
       '2024-06-15'::TIMESTAMP + (i % 500) * INTERVAL '1 day',
       (ARRAY['USD','EUR','GBP','JPY','INR','AED','SGD','CHF','AUD','CAD'])[1 + i % 10],
       CASE WHEN i % 7 = 0 THEN NULL ELSE 'Y' END,
       CASE WHEN i % 5 = 0 THEN NULL ELSE 'name-' || i::STRING END,
       CASE WHEN i % 3 = 0 THEN NULL ELSE (i % 1000)::NUMERIC END
FROM generate_series(1, 50000) AS g(i);

INSERT INTO core.account_advance (account_id, seq_no, active_flag, deleted_flag, advance_amount, bank_code)
SELECT 'A' || lpad((1 + (i % 50000))::STRING, 7, '0'), lpad((i / 50000)::STRING, 5, '0'),
       'Y', 'N', (i % 9973)::NUMERIC * 1.25, 'BANK01'
FROM generate_series(0, 149999) AS g(i);

ANALYZE core.account_master;
ANALYZE core.account_advance;
"""

out = pathlib.Path(__file__).resolve().parent.parent / "sql" / "01_schema.sql"
out.write_text(sql)
print(f"wrote {out}")
